name: simodin
channels:
  - conda-forge
  - cmutel
dependencies:
  - ipykernel
  - nb_conda_kernels
  - brightway25
  - ecoinvent_interface
  - CoolProp
  - fsspec==2025.9.0
  - python==3.12
  - pip:
    - simodin
    - fluprodia
  
